### ISSUE TITLE
Endpoint URL should accept all HTTP methods

### ISSUE THREAD

**Issue by arnellebalane** [uncaughtxcptn/endpoints#17]

**Comment by name3anad** [comment]
@aldnav may be you want to take this ticket.

**Comment by aldnav** [comment]
@name3anad will do.

**Comment by aldnav** [comment]
@name3anad how would you like this to proceed? Do we want users to specify unique response per http method? Something like this perhaps? _just for visualization_ 

![alt example](https://i.imgur.com/btBnJ5g.png)

I might be missing the details here. I'm just guessing and adding `app.router.add_{method}` is what I've done so far. _yet even that is unsure_.

Thanks.

**Comment by name3anad** [comment]
@aldnav as for the UI I defer to @arnellebalane . As for the backend I suppose first you have to edit the Response model/table to accept be able to store http methods and then [visit_endpoint](https://github.com/uncaughtxcptn/endpoints/blob/master/src/endpoints/views.py#L24) view to be a class based views and register it like the [view](https://github.com/uncaughtxcptn/endpoints/blob/master/src/endpoints/routes.py#L15) to control the live status

**Comment by aldnav** [comment]
@name3anad understood 👌

**Comment by arnellebalane** [comment]
@name3anad @aldnav This issue is about making the endpoint URL accept all HTTP methods. Currently, endpoint URLs only accept `GET` and `HEAD` requests because they are defined through `app.router.add_get()`. Other HTTP methods (e.g. `OPTIONS`, `POST`, etc.) should be accepted as well.

**Comment by aldnav** [comment]
>  Other HTTP methods (e.g. OPTIONS, POST, etc.) should be accepted as well.
https://github.com/uncaughtxcptn/endpoints/pull/63 does just that
@name3anad @arnellebalane
