### ISSUE TITLE
Display current auto response values

### ISSUE THREAD

**Issue by arnellebalane** [uncaughtxcptn/endpoints#30]
At the moment, the auto-response form in the endpoint page is always empty at page load. 

Update this to fetch the current auto-response values from the backend and display them on the form.

- [x] Endpoint for fetching auto-response values
- [x] Store auto-response values in Vuex store
- [x] Populate `endpoint-header` response form

**Comment by arnellebalane** [comment]
@name3anad Partially implemented in https://github.com/uncaughtxcptn/endpoints/commits/display-auto-response-values

**Comment by aldnav** [comment]
Branch [display-auto-response-values](https://github.com/uncaughtxcptn/endpoints/commits/display-auto-response-values) is updated. Provides endpoint for fetching auto-response values.
