### ISSUE TITLE
Suggestion: Remove dashes in endpoint hash

### ISSUE THREAD

**Issue by arnellebalane** [uncaughtxcptn/endpoints#33]
@name3anad thoughts about removing the dashes in the endpoint hashes? I think they look "noisy".

```
🤔localhost:8080/da45ea43-dce0-4ec4-93c4-942e36e4293b 
🙌localhost:8080/da45ea43dce04ec493c4942e36e4293b
```

**Comment by arnellebalane** [comment]
@aldnav for me personally, the lowercase hex characters in uuid (as in the examples in the issue description) are more pleasant to look at and therefore I would prefer them. But I believe you can set what alphabet to use for shortuuid?

**Comment by aldnav** [comment]
@arnellebalane no problem. Just throwing suggestions here and there. :smile: . Yes you can set the alphabet to use to generate. But yeah the length isn't the issue here so for the removing dashes part I can use hex and unhex the hash just from the `views.py`. Will submit a PR when I get the time.
