### ISSUE TITLE
Improve WS store

### ISSUE THREAD

**Issue by name3anad** [uncaughtxcptn/endpoints#53]
Currently the websocket connections are stored in the app instance. When running the server in multiple threads there are inconsistencies on the websocket storage since there are now multiple app instances in different threads and they have their own list of websocket connections. Do solve this we need to store the websocket connections somewhere that is shared by all instances of the web server. Redis can probably do this.

**Comment by name3anad** [comment]
http://aioredis.readthedocs.io/en/v1.0.0/start.html#commands-pipelining

**Comment by arnellebalane** [comment]
"Commands pipelining" looks very similar to doing `Promise.all()` in JS :smile_cat:
